lsst-epo/investigations-client

.github/workflows/dev-pull-request.yaml
.github/workflows/dev-push.yaml
Dockerfile

EPO-7898
A few sentences describing the outcome of the change (“fixes a thing”; "adds the stuff") and how you tackled it (“added a prop to prevent lazyloading in the presence of barbara walters”).  How successful is the change?  And how are you measuring that success?
Where should the reviewer look for the change?  Do they review the change on the frontend?  How extensive is the change?  Does it affect Components used in a variety of contexts?  Anything you'd like reviewers to pay particular attention to or questions you have about the change.
- 5 = "Please make sure there are no obvious errors and that you believe it does what it says …

Added workflows for dev deployment

---

components/page/TableOfContents/TableOfContents.stories.tsx
components/page/TableOfContents/TableOfContents.tsx
components/page/TableOfContents/index.ts
components/page/TableOfContents/styles.ts
theme/styles/mixins/appearance.js

JIRA: https://jira.lsstcorp.org/browse/EPO-7975
Add table of contents component
Check Storybook instance
- 3 = "I barely need review on this"
Test that component matches the visuals in XD

[C] Table of Contents

---

components/content-blocks/Questions/index.tsx
components/factories/QuestionFactory/index.tsx
components/questions/InlineQuestion/Multiselect/index.tsx
components/questions/InlineQuestion/Readonly/index.tsx
components/questions/InlineQuestion/Select/index.tsx
components/questions/InlineQuestion/Select/styles.ts
components/questions/InlineQuestion/Text/index.tsx
components/questions/InlineQuestion/Text/styles.ts
components/questions/InlineQuestion/index.tsx
components/questions/InlineQuestion/styles.ts
components/questions/SimpleQuestion/Select/styles.ts
components/questions/SimpleQuestion/index.tsx
components/shapes/questions.ts
components/templates/Page/index.tsx
package.json
yarn.lock

JIRA: https://jira.lsstcorp.org/browse/EPO-8249
Add InlineQuestion components using the same setup as SimpleQuestion. Closes #23

[F] InlineQuestion components

---

.github/workflows/main-pull-request.yaml
.github/workflows/main-push.yaml

Added workflows for int

---

gql/educator-schema/graphql.ts
gql/public-schema/graphql.ts
gql/student-schema/graphql.ts

Updates codegen schema typing after removing GCS plugin from craft

[C] Updates codegen after gcs removal

---

package.json

Merge me when everything else is in and it's time to cut to prod

[C] update for release

---

components/layout/Toaster/styles.ts

JIRA: https://jira.lsstcorp.org/browse/EPO-8801
Fix toaster overlapping nav by pushing it off page and translating toasts upward

[C] fix toaster overlap

---

app/[locale]/[investigation]/[page]/layout.tsx
app/[locale]/[investigation]/review/layout.tsx
components/page/Header/Header.tsx
components/page/Menu/index.ts
components/page/Menu/index.tsx
public/localeStrings/en/translation.json

JIRA: https://jira.lsstcorp.org/browse/EPO-8806
Add logout and review actions to the menu
Change is client-only
- 2 = "I barely need review on this"
- Verify that review link works
- Verify logout shows for logged in users only
- Verify logout works and directs back to home

[C] add logout to main menu

---

app/[locale]/[investigation]/[page]/layout.tsx
app/[locale]/[investigation]/review/layout.tsx
components/page/Header/Header.tsx
components/page/Pager/Pager.tsx
components/page/TableOfContents/TableOfContents.tsx
package.json

For JIRA: "EPO-8900 #IN-REVIEW #comment allow educators access to all pages"
JIRA: https://jira.lsstcorp.org/browse/EPO-8900
Allow educators access to all pages in pager and table of contents

[C] allow educators access to all pages

---

components/templates/InvestigationChildPage/styles.ts

Add a bunch more padding above the pager so we stop getting overlaps

[C] add a bunch more padding

---

.github/workflows/dev-pull-request.yaml
.github/workflows/dev-push.yaml
.github/workflows/main-pull-request.yaml
.github/workflows/main-push.yaml
.github/workflows/main-release-tag.yaml
Dockerfile
components/auth/buttons/GoogleSSO/Button.tsx
components/auth/buttons/GoogleSSO/GoogleSSO.tsx
components/auth/buttons/GoogleSSO/actions.ts
contexts/AuthDialogManager.tsx
package.json
yarn.lock

JIRA: https://jira.lsstcorp.org/browse/EPO-8949
The custom Google Login button is back!  With it we are using the [Auth Code flow](https://developers.google.com/identity/oauth2/web/guides/how-user-authz-works#oauth_20_flows) wherein the client receives an auth `code` from Google after the user auths, serverside we use a Google OAuthClient (part of the Google js SDK) to send this code to a Google OAuth endpoint, along with our `GOOGLE_APP_ID` and `GOOGLE_APP_SECRET`, and Google sends us back the `idToken` (jwt) we need to lookup/auth the user against Craft Users (via the GraphQL Authentication Craft plugin).
This PR is best tested alongside https://github.com/lsst-epo/investigations-client/pull/122.
Run yarn to pick up the newly added Google Auth package.
While it turned out the …

[EPO-8949] Fix Google OAuth

---

components/page/Header/Header.tsx

This reverts commit bef2f5d623798d36c94c1c1cb749287f18a039ba.

Revert "[TEST] For troubleshooting educator's skip"

---

package.json
yarn.lock

Fix error with cross origin missing on images causing app crash in Safari

[B] fix Safari cross origin image error

---

package.json
yarn.lock

[C] cross browser fixes

---

app/api/asset/route.ts
app/api/revalidate/route.ts
components/content-blocks/MagnitudeScatterPlot/index.tsx
components/content-blocks/SupernovaDistanceDistribution/index.tsx
lib/tags.ts

Revalidate GCS asset tags during revalidation process

[C] revalidate datasets

---

components/questions/Review/Widget/SourceSelector/index.tsx
components/questions/Widget/SourceSelector/index.tsx
helpers/widgets.ts

Reviews page was not setting up data in the same way as the widget, created a single helper to handle moshing the data together.
Resolves #185

[B] unified Source Selector helper

---

app/[locale]/layout.tsx
components/hoc/withModal/withModal.tsx
lib/reset.ts
package.json
yarn.lock

Deprecate react-uid and replace with `useId()`

[C] deprecate react-uid

---

app/[locale]/[investigation]/layout.tsx

Add safety when destructuring title in metadata generator

[C] undefined safety for metadata

---

.github/workflows/build-and-push.yaml

Adds a github actions workflow to creates investigations-client deployment for K8s
Verify that image naming is correct and doesn't overlap with current app engine image name
5
No testing

Add build and deploy workflow for k8s

---

.github/workflows/build-and-push.yaml
Dockerfile

Kick off build for int environment
Merging  to deploy k8s image
1
n/a

Create int image for k8s

---

.github/workflows/build-and-push.yaml
Dockerfile

JIRA: https://jira.lsstcorp.org/browse/
What this change does
Update build, push deploy workflow to include main branch on trigger
Notes for reviewers
1
Testing
How did you test this change? Can the reviewer test this change for themselves?
Checklist
This is a breaking change: changes in page data (/src/data/pages/PAGE.json) or scientific data (anything in /static/) and I will notify Product Marketing when it is in prod and user visible.
This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
This change is isolated to a specific page or Component (i.e. it's a one-off)
I don't know what this …

update app name and include 

---

.github/workflows/build-and-push.yaml

Change branch ref for int image to main from master
1

change branch ref to main

---

.github/workflows/build-and-push.yaml
Dockerfile

Changes the reference branch for int trigger
1
How did you test this change?  Can the reviewer test this change for themselves?
n/a

Change int ref branch to main

---

.github/workflows/build-and-push.yaml

Change web hook params from api to client for build and deploy github actions workflow
1

Change webhook params to client image and repo tags

---

next.config.js

Update Build id return to fix git error in container
1

Change build id return

---

next.config.js

Update build id in nextjs.config
1
How did you test this change?  Can the reviewer test this change for themselves?

Update nextjs confign build id
