- components/content-blocks/InvestigationsList/index.js
- components/content-blocks/index.js
- components/factories/ContentBlockFactory.js
- components/templates/Investigations/index.js
- lib/api/entries.js
- lib/api/entry.js
- lib/api/fragments/content-blocks.js
- lib/api/fragments/investigations.js
- lib/api/fragments/page.js
- package.json
- pages/[[...uriSegments]].js
Sets up an investigations landing page for listing the currently available investigations along with a basic investigation page and navigation
- 5
Start development server with EPO-6250 API branch running. Go to the /investigations page to view the currently listed investigations and navigate into them for some sample content.
> [F] Set up investigations landing page

- lib/i18n/client.ts
I also added default values for the `lng` and `ns` params `useTranslation()` so I didn't have to define them every time, but I'm happy to remove that if you're not a fan.
> [B] Fix missing translations in client components

- app/[locale]/[investigation]/[...uriSegments]/page.tsx
- components/answers/SaveForm/SaveForm.tsx
- components/educator-schema/saveAnswersAction.ts
- components/student-schema/saveAnswersAction.ts
- components/templates/InvestigationChildPage/index.tsx
- contexts/StoredAnswersContext.tsx
- gql/educator-schema/gql.ts
- gql/educator-schema/graphql.ts
- gql/student-schema/gql.ts
- gql/student-schema/graphql.ts
- public/localeStrings/en/translation.json
- types/answers.d.ts
Resolves #52 
Resolves #53 
*Note: this PR should be merged only after [the corresponding PR in the API repo](https://github.com/lsst-epo/investigations-api/pull/33/files) is merged.*
This PR updates the client to work with the new resolver in the API so that an entire answer set can be submitted for an investigation in one mutation.
It also adds logic to handle user accounts in a pending state. In such cases, the Save Your Work button is be disabled and a message is shown to users to activate their account. The mutation will also not run, should someone still find a way to submit the form.
- 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"
If any of the following …
> [F] Implement bulk save mutation

- app/[locale]/page.tsx
- components/auth/buttons/SignOut/SignOut.tsx
- contexts/StoredAnswersContext.tsx
This PR makes two changes:
1. On sign out, the user's local storage is cleared. Unfortunately there's not a more granular solution to deleting answers, since we can't really know all the investigations that a user has stored responses for, which we'd need to reference particular keys in storage. But as long as local storage isn't being used for other purposes in the application (and that couldn't also be cleared on sign-out), I think this solution is OK.
2. The StoredAnswersProvider is also updated to initially give priority to answers stored in the DB. There's a bit of logic to only do this the first time the context is loaded. Otherwise DB answers would continue to overwrite local storage on subsequent updates. I don't _love_ the solution, because if someone reloads the page their …
> [B] Improve answer storage logic

- contexts/StoredAnswersContext.tsx
JIRA: https://jira.lsstcorp.org/browse/EPO-8686
Data from server answers was being passed along as JSON strings and getting re-stringified, further nesting it in double quotes and escaped double quotes. This indicated a mismatch between number of times the data was stringified and parsed (stringified data getting re-stringified)
Found where JSON was being passed into JavaScript without being parsed first and fixed.
Before testing on this branch, observe on `develop` that after completing the first few pages of questions and saving then refreshing, that the text input is in double quotes, selects are empty, and widget data does not load. This is because the data being fed in is a string of JSON.
With this branch checked out, complete the same actions and observe that after saving and …
> [B] parse answer data from JSON

- app/[locale]/[investigation]/review/page.tsx
- components/templates/HomePage/index.tsx
- components/templates/HomePage/styles.ts
- components/templates/InvestigationChildPage/index.tsx
- components/templates/InvestigationChildPage/styles.ts
- components/templates/InvestigationLandingPage/index.tsx
- components/templates/InvestigationLandingPage/styles.ts
- components/templates/InvestigationSectionBreakPage/index.tsx
- components/templates/Page/index.tsx
- components/templates/ReferenceContentPage/index.tsx
- components/templates/ReferenceContentPage/styles.ts
JIRA: https://jira.lsstcorp.org/browse/EPO-8793>
Wherever `Container` is used gets the `width="narrow"` prop to approximate the max container width shown in design.  It's still a bit wider than in the design (by around 100px) but feels....fine?
Chances the `Container` on homepage, investigation landing page, investigation child page, review page, and reference content page.
Please visually inspect on all effected page layouts at desktop and mobile screen widths.
> [EPO-8793] Narrower max container width 

- components/content-blocks/InteractionGroupContainer/styles.ts
JIRA: https://jira.lsstcorp.org/browse/EPO-8805
Use negative margins and media queries to make interaction group span full screen width on mobile sizes.
> [C] interaction groups span screen width on mobile

- components/questions/InlineQuestion/Multiselect/index.tsx
- package.json
- yarn.lock
JIRA: https://jira.lsstcorp.org/browse/EPO-8807
Update to latest libraries to get fixed version of SelectListbox that resolves the focus issue in Safari.
Client change, make sure to `yarn` 
In Safari, visit a page with select dropdowns and observe that they can be focused and unfocused.
> [C] update SelectListbox

- components/templates/InvestigationLandingPage/index.tsx
JIRA: https://jira.lsstcorp.org/browse/EPO-8842
Uses email as a fallback when no name has been provided for a user. Username is not available on the user object.
Client-only
Create a new user with no first or last name, check that logging in shows "logged in as [email]"
> [C] use email as fallback for name

- components/auth/dialogs/SignUp/SignUp.tsx
- components/auth/dialogs/SignUp/actions.ts
- components/auth/dialogs/SignUp/styles.ts
- public/localeStrings/en/translation.json
- public/localeStrings/es/translation.json
JIRA: https://jira.lsstcorp.org/browse/EPO-8841
"error" status was not reflecting properly in signup. Address this bug and additionally put an error parser in that interprets the GraphQL errors into a translateable message.
Client-only
- 3
Test the following cases:
- Create a new account with an email that is already signed up
- Create a new account with an invalid email (ex. a@b.)
- Create a new account with a password that does not meet the minimum length (frontend validation was added on this as well so the error catch may be unnecessary)
> [C] add error parser to signup

- components/content-blocks/Image/Image.tsx
- components/content-blocks/Image/styles.ts
For JIRA: "EPO-8856 #IN-REVIEW #comment use Craft caption as fallback"
JIRA: https://jira.lsstcorp.org/browse/EPO-8856
Instead of concatenating the Craft "caption" field to the Canto caption field, use it as a fallback (mostly for i18n)
Client change mainly but the API 
View an image that does not have a caption written in Craft, the caption + credit from Canto should be used. Add a caption in Craft and check again, it should use this caption instead.
> [C] use Craft caption as fallback

- components/content-blocks/Questions/index.tsx
- components/content-blocks/Questions/styles.ts
- components/factories/QuestionFactory/index.tsx
- components/questions/InlineQuestion/index.tsx
- components/questions/InlineQuestion/styles.ts
- components/questions/QuestionNumber/index.tsx
- components/questions/SimpleQuestion/Multiselect/index.tsx
- components/questions/SimpleQuestion/Select/index.tsx
- components/questions/SimpleQuestion/Text/index.tsx
- components/questions/SimpleQuestion/Textarea/index.tsx
- components/questions/SimpleQuestion/index.tsx
- components/questions/SimpleQuestion/styles.ts
- components/questions/TabularQuestion/Select/index.tsx
- components/questions/TabularQuestion/Text/styles.ts
- components/questions/TabularQuestion/index.tsx
- package.json
- types/questions.d.ts
JIRA: https://jira.lsstcorp.org/browse/EPO-8995
Pushes client rendering out on the render tree by having the question number matched in a single component, not a vital change but has the potential to make further changes to stuff like widgets that may need larger libs rendered on the server. 
Also includes an A11Y to remove an incorrectly set `aria-labelledby` attribute.
Client only branch
> [C] question server rendering + a11y fix

- components/auth/buttons/GoogleSSO/actions.ts
- lib/fetch.ts
To be reviewed alongside https://github.com/lsst-epo/investigations-api/pull/80
Please test:
- user creation with google auth and with username + password
- user login with google auth and with username + password
Note for reviewers:
- In my testing the forget password link and the account activation emails are not sending correctly.  I am willing to believe this is a problem unique to local dev and so suggest testing those additional use cases after this work has been released to `dev`.
- You will need an env var for the google secret in addition to the app id for the new client auth code to to work as expected.  @alexgoff you may already have those in there from my previous refactor of this google auth work, but if you need either ping @blnkt in Slack.
> [B] studentAuthData has student object for useFragment arg

- components/content-blocks/Questions/index.tsx
- components/content-blocks/Questions/styles.ts
- components/questions/QuestionNumber/index.tsx
- components/questions/QuestionNumber/styles.ts
For JIRA: "EPO-9125 #IN-REVIEW #comment fix select dropdown behind question text"
Select dropdowns are already given their own stacking context, however since the browser considers items added later in the DOM to be at a higher implicit z-index they end up rendering behind dropdowns in following questions.
To fix this, the questions index among all questions is used to assign a `z-index` to that specific question, in descending order (first question will have the highest z-index)
Change is clientside
- 2
Verified locally on Chrome, Safari, and Firefox. 
- Go to a page with multiple select questions (pages 6 and 10 in Coloring the Universe)
- page 18 for additional …
> [B] fix select dropdown behind question text

- components/dynamic/LightCurveTool/MagnitudeScatterPlot/index.tsx
- components/questions/Review/Widget/SourceSelector/index.tsx
- components/questions/Widget/SourceSelector/index.tsx
- helpers/assets.ts
- helpers/widgets.ts
- package.json
- yarn.lock
Use a smaller image size (240px) to improve source selector loading speeds. Change x, y, and radius values to percentages to avoid future re-mapping of source points.
> [C] Resize source selector images

- components/content-blocks/Image/index.ts
- components/content-blocks/Image/index.tsx
- components/content-blocks/Image/styles.ts
- components/content-blocks/Video/index.tsx
- components/content-blocks/Video/styles.ts
- components/layout/WidgetContainer/styles.ts
- components/page/Body/styles.ts
- helpers/assets.ts
- helpers/index.ts
- theme/styles/base/_base.scss
- types/video.d.ts
Limits the size of images and videos. Each block picks the smaller of two sizes: the natural width/height of the content or the available height of the window between the top nav and the pager. 
Canto image re-sizing has also been re-written to include a better `srcset` and `sizes` so browsers can select a better (and hopefully smaller) image when available.
Resolves #200
> [C] limit image size

- components/calculators/Interactive/index.tsx
- components/calculators/Static/index.tsx
- components/calculators/interactive/index.tsx
- components/calculators/lib/index.ts
- components/calculators/lib/latex.ts
- components/calculators/static/index.tsx
- types/calculators.d.ts
Resolves #209 
Store all calculator values as strings to preserve trailing zeroes. Values are then parsed into numbers before they go into the equation evaluator itself.
> [B] store calculator values as strings

- components/calculators/Interactive/styles.ts
- components/calculators/interactive/styles.ts
- components/content-blocks/Questions/styles.ts
- components/questions/Calculator/index.tsx
- components/questions/Calculator/styles.ts
- components/questions/QuestionNumber/index.tsx
- components/questions/QuestionNumber/styles.ts
Resolves #214 
Remove the `container-type: inline-size` that interferes with z-indexing on dropdown questions and replace with a customized instance of `QuestionNumber` where it is needed as a container for Equations.
> fix: dropdowns behind questions

- components/educator-schema/saveAnswersAction.ts
- components/student-schema/saveAnswersAction.ts
Parse answers before saving so that only `data`, `questionId` and `id` are attached to the `Answer` object that is sent up to the server
Resolves #244
> fix: parse answers before saving

- components/questions/MultipartQuestion/Multiselect/index.tsx
It was possible for multiselects to receive `null` instead of an empty array which would cause an error to be thrown when opening the list dropdown. Add destructuring fallbacks to make sure an empty array is the default value passed.
Resolves #249
> fix: multiselect receive empty array instead of null

- app/api/revalidate/route.ts
- lib/fetch/index.ts
- next-env.d.ts
Add the same setup that the rubin-obs-client is using in it's `urql` client to re-enable Next's data caching
> fix: add 'force-cache' to query

- .github/workflows/build-and-push.yaml
- Dockerfile
- Updated the int environment branch from `master` to `main` in the new workflow for k8s deployment
- Updated the Dockerfile to make the site build its own optional step. It still runs by default but can be disabled by making the build argument `RUN_BUILD` false.
Rubber stamp me!
Pattern has been tested on the Rubinobs main site
> K8s updates

- .github/workflows/build-and-push.yaml
- package.json
- yarn.lock
A few sentences describing the outcome of the change (“fixes a thing”; "adds the stuff") and how you tackled it (“added a prop to prevent lazyloading in the presence of barbara walters”).  How successful is the change?  And how are you measuring that success?
Where should the reviewer look for the change?  Do they review the change on the frontend?  How extensive is the change?  Does it affect Components used in a variety of contexts?  Anything you'd like reviewers to pay particular attention to or questions you have about the change.
- 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"
- …
> chore(release)
